### ISSUE TITLE
Tracking issue for Issue 1

### ISSUE THREAD

**Issue by Folyd** [RustMagazine/rustmagazine#11]
Issue 1 will be released with at most 10 articles end of January 2023. Here is the article list:

- [x] [Announcing Rust Magazine](https://rustmagazine.github.io/announcing/)
- [x] VecDeque::resize() optimization #7 
- [x] MiniLSM: A Tutorial of Building Storage Engine in a Week using Rust #9 
- [x] Interview with weihanglo #10 
- [x] How I Contribute to Rust Compiler #16 
- [x] Rust for Linux Brief Introduction #19 
- [x] 2022 Review | The adoption of Rust in Business #26
- [x] Added the hidden control flow #24

**Comment by Folyd** [comment]
We'll release the first issue soon, please take a look at those articles whenever you get a chance. Much appreciation to our editors.  @LCrossman @dmosc @ZhangHanDong @macko76

**Comment by dmosc** [comment]
Sg! All articles look great!

I'm going to work on one for the next issue.

Thanks for the summary.
