### ISSUE TITLE
Tracking issue for Issue 2

### ISSUE THREAD

**Issue by Folyd** [RustMagazine/rustmagazine#44]
Issue 2 will be released end of February 2023. Here is the article list:

- [x] Optimize Rust Binary Search #56 @Folyd 
- [x] Stupidly effective ways to optimize Rust compile time #57  @xxchan
- [x] How I Designed the API for Backon, a User-Friendly Retry Crate #67 
- [x] Write a SQL Optimizer using Egg #69 @wangrunji0408
- [x] #68 @ZhangHanDong 
- [x] Interview with Sunli #65 
- [x] Applicative command line parser #64
- [ ] https://github.com/RustMagazine/rustmagazine/pull/23
- [ ] https://github.com/RustMagazine/rustmagazine/pull/58 @dmosc

**Comment by Folyd** [comment]
Do you have any article or author for Issue 2? Feel free to update the article list above. 😸 @LCrossman @malagant @macko76 @mfrw @dmosc
