### ISSUE TITLE
Tracking issue for Issue 3

### ISSUE THREAD

**Issue by Folyd** [RustMagazine/rustmagazine#74]
Issue 3 will be released in early April 2023. Here is the article list:

- [x] Interview with [robjtede](https://github.com/robjtede) @Folyd 
- [x] How Rust Search Extension index top 20k crates #83 @Folyd 
- [x] Pursuit of Performance on Building a JavaScript Compiler #80  @Boshen
- [x] TaskStatsAlloc: Fine-grained memory statistics in Rust #87 @TennyZhuang
- [x] Comprehensive Understanding of Unsafe Rust #81 @ZhangHanDong 
- [x] Is Zig safer than Unsafe Rust? #81 @ZhangHanDong 
- [x] Bridging Async and Sync Rust Code - A lesson learned while working with Tokio #75
- [x] Optimizing Compilation for Databend #90

**Comment by Boshen** [comment]
I'll submit a piece on "My adventure on writing a JavaScript linter". It'll mostly be about how I struggled and solved some of the problems I faced in my project [oxc](https://github.com/Boshen/oxc). 

I'll probably submit an outline by this week, and then follow up with some details by next week or the week after.

**Comment by Folyd** [comment]
https://rustmagazine.org/issue-3/ is out.
